### ISSUE TITLE
links with ~ don't get parsed

### ISSUE THREAD

**Issue by CheloXL** [meleze/Meleze.Web#11]
Hi,

I have a bunch of things (images, js) with paths relative to the root (ex: <img src="~/css/logo.png" alt="" />). The new parser doesn't expand the ~ as it should.

Also, it is strange that this happens only inside the BODY tag, as all the links to css/js on the header are correctly parsed...

**Comment by DzonnyDZ** [comment]
This happens to me as well, is there any way to solve it?
