### ISSUE TITLE
meleze.web for mvc4 not work properly

### ISSUE THREAD

**Issue by CengizPoyraz** [meleze/Meleze.Web#12]
PartialViews are not minified when I try it for mvc4! In MVC3, meleze.web works  perfectly!

What may cause this?

**Comment by CengizPoyraz** [comment]
this bug also exists in sections minification!

**Comment by CengizPoyraz** [comment]
FlattenHTMLAttributes does not check the markups in the razor sections... I think we need a recursive flatten method..

**Comment by davistan** [comment]
Just tested and it doesn't minify the output generated from blocks. I'm using script block extension like in this page http://forloop.co.uk/blog/managing-scripts-for-razor-partial-views-and-templates-in-asp.net-mvc

**Comment by SergiiGalai** [comment]
The same issue with sections minification. I see this issue is opened for a year...

**Comment by meleze** [comment]
@davistan Script block extensions won't be minified (directly at least) by Meleze because it performs the minification at compile time while the block extensions are executed at runtime.

**Comment by fqf** [comment]
It doesn't minify all my pages.
For example for my login page I've got this:

![1](https://f.cloud.github.com/assets/628607/2169320/0458fdbe-9558-11e3-9347-f3e68e0ab46e.png)

So it doesn't minify all the whitespaces.
