### ISSUE TITLE
URL-s in inline javascript strings

### ISSUE THREAD

**Issue by SoonDead** [meleze/Meleze.Web#14]
Try this:

``` javascript
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "http://connect.facebook.net/hu_HU/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    } (document, 'script', 'facebook-jssdk'));
</script>
```

It works fine unminified, but

You get:

SyntaxError: unterminated string literal

```
....createElement(s); js.id = id; js.src = "http: fjs.parentNode.insertBefore(js, f...
```

Removing comments from inline scripts needs a little more advanced logic as this will just kill url-s in strings.

This is gamebreaking for me, I'm going to disable minification until this gets solved.

**Comment by meleze** [comment]
I have enhanced the javascript parser to take strings into account when looking for comments.

The fix is in the 1.4.4 release.
