### ISSUE TITLE
Not working within an Area

### ISSUE THREAD

**Issue by brgrz** [meleze/Meleze.Web#4]
I'm having issue getting this to work within an Area. It is working fine after I've added it into the root Views/web.config. Now I've also added it to the Area/Views/web.config and it does not minify. 

Other than that I think this package has a future, I really like my HTML minified and whitespace free.

**Comment by meleze** [comment]
OK, I have not tested with Areas and I am a bit surprised that it's not working.
I will take a look and I will get you updated :-)

**Comment by meleze** [comment]
I made some tests with Areas and it is minifying correctly.

Razor caches the compiled pages. Perhaps you have executed one of the area's views before enabling the minifier.
You can try to update your views (just to change the file timestamp) and this should force Razor to minify the page.

Tell me if it is solving your problem.
