### ISSUE TITLE
The parser provided to the ParserContext was not a Markup Parser

### ISSUE THREAD

**Issue by robertohuertasm** [meleze/Meleze.Web#5]
Hi, I just wanted to try your dll in a mvc 4 beta application but I keep on getting this exception:

The parser provided to the ParserContext was not a Markup Parser

Any help?

**Comment by meleze** [comment]
Can you send me the view cshtml and the complete stack trace?

**Comment by meleze** [comment]
I have released a new version of the MVC4 package. This should fix your problem.
