### ISSUE TITLE
Meleze.Web is not working.

### ISSUE THREAD

**Issue by jobzky** [meleze/Meleze.Web#6]
When you search in Google most complaints about your dll is that it's not working. You even didn't provide sample MVC application that use this dll. I tried it also even installing the dll to GAC but it's not working. I even published the site to IIS but still not working. Your latest version from nuget will automatically add the configuration sections to web.config but still we cannot see that this ddl is working. Do we need to creates some class files or what? I hope you will provide comprehensive and complete details on how to configure this.

**Comment by meleze** [comment]
As explained in the README, you just have to replace the RazorHostFactory in your Views/web.config. It should looks like something like that:
&lt;configuration&gt;
  &lt;system.web.webPages.razor&gt;
    &lt;host factoryType="Meleze.Web.Razor.MinifyHtmlWebRazorHostFactory, Meleze.Web, Version=1.4.0.1, Culture=neutral, PublicKeyToken=0a868b5321967eda" /&gt;
  &lt;/system.web.webPages.razor&gt;
&lt;/configuration&gt;

You may have to clean your application to force Razor to recompile the pages with the minifier.

**Comment by jobzky** [comment]
I got an error "Expression of type 'Meleze.Web.Razor.MinifyHtmlWebRazorHostFactory' cannot be used for return type 'System.Web.WebPages.Razor.WebRazorHostFactory'"

I did the following
1. Installed Meleze.Web from nuget. 
2. I changed "Views/web.config" from 
host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" /

to
host factoryType="Meleze.Web.Razor.MinifyHtmlWebRazorHostFactory, Meleze.Web, Version=1.4.0.1, Culture=neutral, PublicKeyToken=0a868b5321967eda" /

**Comment by meleze** [comment]
Your configuration seems OK.

Can you send the full stack trace ?

**Comment by jobzky** [comment]
Stack Trace:

[ArgumentException: Expression of type 'Meleze.Web.Razor.MinifyHtmlWebRazorHostFactory' cannot be used for return type 'System.Web.WebPages.Razor.WebRazorHostFactory']
   System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters) +4044644
   System.Linq.Expressions.Expression.Lambda(Expression body, String name, Boolean tailCall, IEnumerable`1 parameters) +73
   System.Linq.Expressions.Expression.Lambda(Expression body, Boolean tailCall, IEnumerable`1 parameters) +62
   System.Linq.Expressions.Expression.Lambda(Expression body, ParameterExpression[] parameters) +64
   System.Web.WebPages.Razor.WebRazorHostFactory.CreateFactory(String typeName) +94
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +72
   System.Web.WebPages.Razor.WebRazorHostFactory.CreateHostFromConfigCore(RazorWebSectionGroup config, String virtualPath, String physicalPath) +237
   System.Web.WebPages.Razor.WebRazorHostFactory.CreateHostFromConfig(String virtualPath, String physicalPath) +57
   System.Web.WebPages.Razor.RazorBuildProvider.CreateHost() +17
   System.Web.WebPages.Razor.RazorBuildProvider.EnsureGeneratedCode() +60
   System.Web.WebPages.Razor.RazorBuildProvider.get_CodeCompilerType() +31
   System.Web.Compilation.BuildProvider.GetCompilerTypeFromBuildProvider(BuildProvider buildProvider) +59
   System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders() +209
   System.Web.Compilation.BuildProvidersCompiler.PerformBuild() +34
   System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) +9817305
   System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) +299
   System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) +103
   System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) +165
   System.Web.Compilation.BuildManager.GetObjectFactory(String virtualPath, Boolean throwIfNotFound) +33
   System.Web.Mvc.BuildManagerWrapper.System.Web.Mvc.IBuildManager.FileExists(String virtualPath) +9
   System.Web.Mvc.BuildManagerViewEngine.FileExists(ControllerContext controllerContext, String virtualPath) +41
   System.Web.Mvc.VirtualPathProviderViewEngine.GetPathFromGeneralName(ControllerContext controllerContext, List`1 locations, String name, String controllerName, String areaName, String cacheKey, String[]& searchedLocations) +140
   System.Web.Mvc.VirtualPathProviderViewEngine.GetPath(ControllerContext controllerContext, String[] locations, String[] areaLocations, String locationsPropertyName, String name, String controllerName, String cacheKeyPrefix, Boolean useCache, String[]& searchedLocations) +288
   System.Web.Mvc.VirtualPathProviderViewEngine.FindView(ControllerContext controllerContext, String viewName, String masterName, Boolean useCache) +136
   System.Web.Mvc.<>c__DisplayClassc.<FindView>b__b(IViewEngine e) +24
   System.Web.Mvc.ViewEngineCollection.Find(Func`2 lookup, Boolean trackSearchedPaths) +141
   System.Web.Mvc.ViewEngineCollection.FindView(ControllerContext controllerContext, String viewName, String masterName) +181
   System.Web.Mvc.ViewResult.FindView(ControllerContext context) +109
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +121
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +23
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +242
   System.Web.Mvc.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b() +21
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +177
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +324
   System.Web.Mvc.Controller.ExecuteCore() +106
   System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) +91
   System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext) +10
   System.Web.Mvc.<>c__DisplayClassb.<BeginProcessRequest>b__5() +34
   System.Web.Mvc.Async.<>c__DisplayClass1.<MakeVoidDelegate>b__0() +19
   System.Web.Mvc.Async.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +62
   System.Web.Mvc.<>c__DisplayClasse.<EndProcessRequest>b__d() +48
   System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action f) +7
   System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action) +22
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +60
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9478661
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +178

**Comment by meleze** [comment]
Is your application an ASP.NET  MVC 3.0 application?

If this is the case, you have to use the Meleze 1.3 package (as the Razor internals are completely different between MVC3 and 4, there are 2 distincts implementations of Meleze).

**Comment by jobzky** [comment]
Hi Thanks for the help it's now working fine. I like your approach since it does not incur run time performance. I tried some approach of other developers but their approach incur run time performance that is the page size was reduced by almost 100% but the time of the completion of request of the page is double.

One thing that I noticed by the way is that the javascript and css files are not compressed even if I added the nodes to appsettings on the web.config. Does version 1.3 do not compressed those files?

**Comment by meleze** [comment]
Javascript compression needs the Microsoft Ajax Minifier dll to be referenced in the web application (http://ajaxmin.codeplex.com/)

When Meleze find the AjaxMin, it calls it to minify the inline Javascript.
I have just released a new package that also minifies the inline CSS.

**Comment by jobzky** [comment]
issue close

**Comment by sachchidanandPandey** [comment]
I have same kind  of Problem. I am using MVc razor 4.0
