### ISSUE TITLE
Meleze.Web does not remove javascript comments

### ISSUE THREAD

**Issue by jobzky** [meleze/Meleze.Web#7]
Hi I tried putting this on my sample page

 script type="text/javascript"
    //This is an alert
    alert("This is an alert");
/script

and the compressed page rendered the above script as 

script type="text/javascript">//This is an alert alert("This is an alert"); script

Notice that Meleze.Web will concatenate the javascript lines along with a comment line making the rests as part of the comments thus the page will not execute the javascript functions.

**Comment by meleze** [comment]
Hum, this problem won't happen if you have the Microsoft Ajax Min dll referenced in your application.

I have just released a new package version that fix the bug when AjaxMin is not available.

**Comment by jobzky** [comment]
It's working fine now. Issue close
