### ISSUE TITLE
Problem with Nuget

### ISSUE THREAD

**Issue by andyscott12** [meleze/Meleze.Web#9]
It seems that when you are using Nuget - it has a problem in that it detects [if you are using MVC 3.0] that you must upgrade. 

However, then it installs 1.4.0.3 and if you attempt to reference 1.3.0.3 - it will error with 

`Could not locate Razor Host Factory type: Meleze.Web.Razor.MinifyHtmlWebRazorHostFactory, Meleze.Web`

Are you able to sort out the packages so 1.3.0.3 updates only ASP.NET MVC 3.0 and 1.4.0.3 upgrades MVC 4 ?

**Comment by meleze** [comment]
There is a version compatibility marker in nuget. I will test if I can mark 1.4 not compatible with 1.3.
In the worst case, we can publish to distinct packages (Meleze.Web for the last MVC version and Meleze.Web3 for MVC 3)

**Comment by meleze** [comment]
In the last Nuget versions, you can edit your packages.config to restrict the updates for MVC3

<packages>
<package id="Meleze.Web" version="1.3.5" allowedVersions="[1.3,1.4)" />
</pacakges>

The "allowedVersions" attribute prevent upgrades to version 1.4.
